### ISSUE TITLE
Install and configure LoRa concentrator driver & semtech packet forwarder

### ISSUE THREAD

**Issue by traffael** [Octanis1/Octanis1-Field-Station#2]
Install and configure the LoRa base station driver on the RaspberryPi for our IMST iC880A. 

HAL for LoRa concentrator:  https://github.com/ttn-zh/lora_gateway

Packet forwarding software. Converts LoRa packets to UDP for UDP server to receive (down and upstream packets work): https://github.com/TheThingsNetwork/packet_forwarder/tree/master/poly_pkt_fwd

**Comment by bitmorse** [comment]
Eloi installed Debian and this:  https://github.com/kersing/Raspberry-PI-Link-Labs-LoRaWAN-Gateway

Testing this now.
