### ISSUE TITLE
Install brocaar's loraserver and lora-gateway-bridge

### ISSUE THREAD

**Issue by traffael** [Octanis1/Octanis1-Field-Station#3]
Must be able to receive and send LoRa packets. Integrate this with the previously implemented message buffer that is able to communicate with APM planner.

**Comment by bitmorse** [comment]
evaluate Luc P.'s Loradb and this https://github.com/brocaar/loraserver

**Comment by traffael** [comment]
done, currently configuring monit for unattended startup and monitoring of loraserver and lora-gateway-bridge processes.  see http://wiki.octanis.org/orb/fieldbasestation
