### ISSUE TITLE
Design Case and power supply for the Field station

### ISSUE THREAD

**Issue by traffael** [Octanis1/Octanis1-Field-Station#4]
Content: 
- RaspberryPi
- Battery + Power system
- LoRa gateway 
- u-blox M8P eval kit

Connections to the outside: 
- Ethernet port of RaspberryPi.
- PV module connector
- Power adapter connector for manual battery charger

Antennas: 
- dGPS
- LoRa
- UHF module for dGPS 

Use our EPS (https://github.com/Octanis1/Octanis1-Electronics/tree/master/octanis_eps/v1.0) to supply required voltages and charge batteries with 2 possible inputs:  Solar cells or 5V / 9V power adapter (slight modification needed to switch between the two modes --> Maximum power tracking MPP to be adapted)

Other requirements: 
- Good thermal insulation
- Weather-proof
- Wind proof (possibility to attach to ground)

Update documentation here: http://wiki.octanis.org/orb/mom#base_stations with complete system drawing and photo

**Comment by bitmorse** [comment]
Jeroen is currently working on the tripod mount and will subsequently go on to assemble the aluminium frame.
