### ISSUE TITLE
Create a UDP to MQTT bridge

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-Field-Station#5]
This bridge receives UDP packets from APM Planner containing MAVLink payloads and sends them out to the MQTT server. It must also listen to incoming MQTT packets and relay these to the same UDP endpoint.

**Comment by bitmorse** [comment]
Read this first: http://wiki.octanis.org/orb/fieldbasestation

**Comment by jajoe** [comment]
Done. We just have to change the ports and topics?

**Comment by jajoe** [comment]
You can close this issue I believe, everything seem to be OK :-)
